  - name: Install Nginx
  package:
    name: nginx
    state: present
  become: yes

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file }}"
  become: yes
  notify: Restart Nginx

- name: Ensure Nginx service is running
  service:
    name: "{{ nginx_service_name }}"
    state: started
    enabled: yes
  become: yes

- name: Allow traffic on port 80
  ufw:
    rule: allow
    name: 'Nginx Full'
    port: "{{ nginx_port }}"
    proto: tcp
  become: yes
  when: ansible_facts.packages['ufw'] is defined
