---
- name: Start an Nginx container and ensure it is always running
  hosts: all
  become: yes
  tasks:
    - name: Ensure the Nginx container is started and always running
      docker_container:
        name: nginx_container
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "8080:80" # Maps port 8080 on the host to port 80 in the container
